---
title: "LabEx4-Data Cleaning in R"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---
### Reg. No: 18BCE1010

### Name: R. Harini

## Setup
```{r}
rm(list=ls())
```


### Load packages if any using library(packagename)
```{r}
library(dplyr)
library(tidyr)
```


### Load data
```{r}
dataset <- read.csv("loans data.csv", stringsAsFactors = FALSE)
```



### Clean the data by including appropriate comments





* * *

```{r}
#1. checking the structure of dataset and understanding the dataset
str(dataset)
class(dataset)
colnames(dataset)

```
```{r}
#2. checking the class of ID
class(dataset$ID)
```
```{r}
#3 checking the class and structure of Amount.Requested and cleaning its content if any missing or NA values or different values are present
class(dataset$Amount.Requested)
str(dataset$Amount.Requested)
```
```{r}
dataset %>% distinct(Amount.Requested)
dataset <- dataset %>% mutate(Amount.Requested = replace(Amount.Requested , Amount.Requested==".", NA))
dataset$Amount.Requested
```
```{r}
dataset$Amount.Requested <- as.numeric(dataset$Amount.Requested)
dataset <- dataset %>% mutate(Amount.Requested = replace(Amount.Requested , is.na(Amount.Requested), mean(Amount.Requested, na.rm = TRUE)))
sum(is.na(dataset$Amount.Requested))
```
```{r}
#4. checking the class and structure of Amount.Funded.By.Investors and cleaning it to appropriate stage
class(dataset$Amount.Funded.By.Investors)
str(dataset$Amount.Funded.By.Investors)
dataset%>%
  distinct(Amount.Funded.By.Investors)
```

```{r}
dataset <- dataset %>% mutate(Amount.Funded.By.Investors = replace(Amount.Funded.By.Investors , Amount.Funded.By.Investors==".", NA))
dataset$Amount.Funded.By.Investors
```
```{r}
dataset$Amount.Funded.By.Investors  <- as.numeric(dataset$Amount.Funded.By.Investors)
dataset <- dataset %>% mutate(Amount.Funded.By.Investors = replace(Amount.Funded.By.Investors , is.na(Amount.Funded.By.Investors), mean(Amount.Funded.By.Investors, na.rm = TRUE)))
class(dataset$Amount.Funded.By.Investors)
sum(is.na(dataset$Amount.Requested))
```
```{r}
#5. checking if there are any na/nan values present in interest.rate 
dataset %>% summarise(misscnt = sum(is.na(Interest.Rate)))
```
```{r}
#6. removing the % in interest.rate and making it as an integer class
class(dataset$Interest.Rate)
dataset%>%
  distinct(Interest.Rate)
dataset <- dataset %>% mutate(Interest.Rate = as.numeric(gsub("%" , "" , Interest.Rate)))
class(dataset$Interest.Rate)
dataset$Interest.Rate
```
```{r}
#7. check for any NA values in loan.length and replace it with median of loan.length by first removing the 'months' keyword
sum(is.na(dataset$Loan.Length))
dataset%>%
  distinct(Loan.Length)
dataset <- dataset %>% mutate(Loan.Length = as.numeric(gsub("months" , "" , Loan.Length)))
```
```{r}
dataset <- dataset %>% mutate(Loan.Length = replace(Loan.Length , is.na(Loan.Length), median(Loan.Length, na.rm = TRUE)))
dataset %>% summarise(misscnt = sum(is.na(Loan.Length)))
class(dataset$Loan.Length)
dataset$Loan.Length
```
```{r}
#8. checking if any inconsistent value exists in loan.purchase
dataset %>% summarise(misscnt = sum(is.na(Loan.Purpose)))
class(dataset$Loan.Purpose)
str(dataset$Loan.Purpose)
dataset %>% summarise(misscnt = sum(Loan.Purpose=="."))

```
```{r}
#9. replace the NA in loan.purpose with 'not specified'
dataset$Loan.Purpose <- as.character(dataset$Loan.Purpose)
dataset <- dataset %>% mutate(Loan.Purpose = replace(Loan.Purpose , is.na(Loan.Purpose), "not specified" ))
class(dataset$Loan.Purpose)
dataset %>% distinct(Loan.Purpose)

```
```{r}
#10 . checking if any inconsistent value exists in Debt.To.Income.Ratio and replacing it with the median by removing the % symbol
class(dataset$Debt.To.Income.Ratio)
dataset %>% summarise(misscnt = sum(is.na(Debt.To.Income.Ratio)))
dataset%>%
  mutate(Debt.To.Income.Ratio=as.numeric(gsub("%","",Debt.To.Income.Ratio )))
```
```{r}
dataset <- dataset %>% mutate(Debt.To.Income.Ratio = as.numeric(gsub("%" , "" , Debt.To.Income.Ratio)))
sum(is.na(dataset$Debt.To.Income.Ratio))
dataset <- dataset %>% mutate(Debt.To.Income.Ratio = replace(Debt.To.Income.Ratio , is.na(Debt.To.Income.Ratio), median(Debt.To.Income.Ratio, na.rm = TRUE)))
dataset %>% summarise(misscnt = sum(is.na(Debt.To.Income.Ratio)))
class(dataset$Debt.To.Income.Ratio)
sum(is.na(dataset$Debt.To.Income.Ratio))
```
```{r}
#11. checking if there is any inconsistent data in state
class(dataset$State)
dataset %>% distinct(dataset$State)
```
```{r}
#12. removing . and na values from state and mentioning it as 'not specified'
dataset=read.csv("loans data.csv", stringsAsFactors = FALSE)
dataset<-dataset%>%mutate(State=gsub(".", "",State))

dataset <- dataset %>% mutate(State = replace(State , State==".", NA))
dataset$State <- as.character(dataset$State)
dataset <- dataset %>% mutate(State = replace(State , is.na(State), "not specified" ))
class(dataset$State)
dataset %>% distinct(dataset$State)
```
```{r}
#12. checking if there is any inconsistent data in home.ownership
class(dataset$Home.Ownership)
dataset %>% distinct(dataset$Home.Ownership)
```
```{r}
#13. replacing NA with 'not specified
dataset$Home.Ownership <- as.character(dataset$Home.Ownership)
dataset <- dataset %>% mutate(Home.Ownership = replace(Home.Ownership , is.na(Home.Ownership), "not specified" ))
class(dataset$Home.Ownership)
dataset %>% distinct(dataset$Home.Ownership)
```
```{r}
#14. checking if there exists any incosistent value in monthly.income
dataset %>% summarise(misscnt = sum(is.na(Monthly.Income)))
class(dataset$Monthly.Income)
str(dataset$Monthly.Income)

```
```{r}
#15. replacing all na values with mean monthly.income
dataset <- dataset %>% mutate(Monthly.Income = replace(Monthly.Income , is.na(Monthly.Income), mean(Monthly.Income, na.rm = TRUE)))
dataset %>% summarise(misscnt = sum(is.na(Monthly.Income)))
```
```{r}
#16. checking the type of fico.range and creating two columns fico.low and fico.high
class(dataset$FICO.Range)
dataset %>% summarise(misscnt = sum(is.na(FICO.Range)))
dataset %>% summarise(misscnt = sum(FICO.Range=="."))
```
```{r}
dataset <- dataset %>% mutate(Fico.low = substr(FICO.Range,1,3 ))
dataset$Fico.low
dataset <- dataset %>% mutate(Fico.high = substr(FICO.Range,5,7 ))
dataset$Fico.high
```
```{r}
#17. checking if there exists any inconsistent data in open credit lines
class(dataset$Open.CREDIT.Lines)
dataset %>% summarise(misscnt = sum(is.na(Open.CREDIT.Lines)))
dataset %>% summarise(misscnt = sum(Open.CREDIT.Lines=="."))
```
```{r}
#18. replacing na values with the median of oopen credit lines
dataset$Open.CREDIT.Lines  <- as.numeric(dataset$Open.CREDIT.Lines)
dataset <- dataset %>% mutate(Open.CREDIT.Lines = replace(Open.CREDIT.Lines , is.na(Open.CREDIT.Lines), median(Open.CREDIT.Lines, na.rm = TRUE)))
class(dataset$Open.CREDIT.Lines)
```
```{r}
#19. checking the values of revolving.credit.balance
class(dataset$Revolving.CREDIT.Balance)
dataset$Revolving.CREDIT.Balance
dataset %>% summarise(misscnt = sum(is.na(Revolving.CREDIT.Balance)))
dataset %>% summarise(misscnt = sum(Revolving.CREDIT.Balance=="."))
```
```{r}
#20 replacing na values with the mean of revolving credit balance
dataset$Revolving.CREDIT.Balance  <- as.numeric(dataset$Revolving.CREDIT.Balance)
dataset <- dataset %>% mutate(Revolving.CREDIT.Balance = replace(Revolving.CREDIT.Balance , is.na(Revolving.CREDIT.Balance), mean(Revolving.CREDIT.Balance, na.rm = TRUE)))
class(dataset$Revolving.CREDIT.Balance)

```
```{r}
#21 checking inquiries in last  months attribute
class(dataset$Inquiries.in.the.Last.6.Months)
dataset %>% summarise(misscnt = sum(is.na(Inquiries.in.the.Last.6.Months)))
dataset %>% summarise(misscnt = sum(Inquiries.in.the.Last.6.Months=="."))
```
```{r}
#22 replacing na values with 0
dataset <- dataset %>% mutate(Inquiries.in.the.Last.6.Months = replace(Inquiries.in.the.Last.6.Months , is.na(Inquiries.in.the.Last.6.Months), 0)) 
dataset %>% summarise(misscnt = sum(is.na(Inquiries.in.the.Last.6.Months)))
```
```{r}
#23 checking the consistency of employment length values
class(dataset$Employment.Length)
dataset %>% distinct(Employment.Length)
```
```{r}
# 24 changing the n/a and . values to NA and replacing all the NA values with '1 year'
dataset <- dataset %>% mutate(Employment.Length = replace(Employment.Length , Employment.Length==".", NA))
dataset <- dataset %>% mutate(Employment.Length = replace(Employment.Length , Employment.Length=="n/a", NA))
dataset <- dataset %>% mutate(Employment.Length = replace(Employment.Length , is.na(Employment.Length), "1 year"))
class(dataset$Employment.Length)
dataset<-dataset%>%mutate(Employment.Length=gsub("year","",Employment.Length))
dataset<-dataset%>%mutate(Employment.Length=gsub("s","n",Employment.Length))
dataset %>% distinct(Employment.Length)
```

* * *

##  Frame any 5 Questions on data manipulation and Corresponding Code & Output

```{r}
#1. Display the loan length for interest rates above 10%
dataset%>%
  filter(Interest.Rate>10)%>%
  dplyr::select(Loan.Length, Interest.Rate)
```

```{r}
#2. Display Amount Requested and Amount Funded By Investors in Descending order based on the interest rate
dataset%>%
  arrange(desc(Interest.Rate))%>%
  dplyr::select(Amount.Funded.By.Investors, Amount.Requested, Interest.Rate)
```

```{r}
#3. Display the mean of Amount Requested grouped by State
dataset%>%
  group_by(State)%>%
  summarise(mean(Amount.Requested))
```
```{r}
#4. Display the mean Monthly Income of those whose Home Ownership is Mortgage
dataset%>%
  filter(Home.Ownership=="MORTGAGE")%>%
  dplyr::select(Monthly.Income, Home.Ownership)
```
```{r}
#5. Display the Debt to Income ratio of those whose House is on Mortgage. Group the output by states
dataset%>%
  filter(Home.Ownership=="MORTGAGE")%>%
  group_by(State)%>%
  dplyr::select(Debt.To.Income.Ratio, Home.Ownership, State)
```



* * *




