---
title: "Lab10_18BCE1010"
output: html_document
---
# Name: R.Harini
# Reg No: 18BCE1010
## Dataset: Credit Risk Dataset

```{r}
rm(list=ls())
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
```

```{r}
df=read.csv("credit_risk.csv", stringsAsFactors = TRUE)
colnames(df)[1]="person_age"
```

```{r}
str(df)
```

```{r}
sum(is.na(df))
df=na.omit(df)
sum(is.na(df))
```
### Exploratory Data Analysis
```{r}
table(df$person_home_ownership)
```

```{r}
hist(df$person_age, col="cyan", main="Distribution of Age")
```


```{r}
d=df%>%
  group_by(person_home_ownership)%>%
  summarise(avg_loan_amt=mean(loan_amnt))

ggplot(d, aes(x=person_home_ownership, y=avg_loan_amt, fill=person_home_ownership))+geom_bar(stat = "identity")+theme_minimal()+ggtitle(" Home Ownership vs Avg Loan Amt")

```
### Mean of the age applying for loan
```{r}
mean(df$person_age)
```
```{r}
ggplot(df, aes(x=person_emp_length, y=person_age))+geom_smooth(aes(color=loan_grade),se= FALSE)+facet_grid(loan_grade~.)
```

### Pie chart for Loan intents
```{r}
p=table(df$loan_intent)
pie(p)
```
```{r}
d=df%>%
  group_by(loan_grade)%>%
  summarise(avg_person_income=mean(person_income))
d

ggplot(d, aes(x=loan_grade, y=avg_person_income, fill=loan_grade))+geom_bar(stat = "identity")+theme_minimal()
```
 
```{r}
ggplot(df, aes(loan_int_rate, loan_percent_income, color=cb_person_cred_hist_length))+geom_point()+ggtitle("Loan Interest Rate vs Loan % income")

```

```{r}
ggplot(df, aes(loan_grade, fill=loan_grade))+geom_bar()+facet_wrap(~loan_intent)+theme_minimal()
```

```{r}
ggplot(df, aes(cb_person_cred_hist_length))+geom_bar()
```

```{r}
boxplot(df$loan_int_rate, main="Loan Int Rate")
```
```{r}
hist(df$person_income, col="red", main="Distribution of Person Income")
```

 
### ANOVA
```{r}
a=aov(loan_amnt~person_home_ownership,df)
summary.aov(a)
```
#### Variables such as "cb_person_cred_hist_length", "cb_person_default_on_file" and "loan_int_rate" are insignificant due to their p-values

```{r}
TukeyHSD(a,which="person_home_ownership")
```


```{r}
library(car)
leveneTest(loan_amnt~person_home_ownership, df)
```

```{r}
a2=aov(loan_amnt~person_home_ownership*loan_intent,df)
summary(a2)
```

```{r}
TukeyHSD(a2, which="loan_intent")

```


### Regression modelling
```{r}
m1=lm(loan_amnt~., df)
summary(m1)
```


```{r}
plot(m1)
```


```{r}
m2=lm(loan_amnt~.-cb_person_cred_hist_length-cb_person_default_on_file-loan_int_rate,df)
summary(m2)
```

```{r}
plot(m2)
```

