---
title: "LabEx2-Data frame Basics & Indexing"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---
### Reg. No: <your reg.no.here>
18BCE1010

### Name:<your name here>
R. Harini

## Setup

```{r}
rm(list=ls())
```

### Load packages if any using library(packagename)
```{r}
library(MASS)
```

### Load data
```{r}
df=na.omit(survey)
```


* * *

## Part 1: Data (Chosen Dataset, Description of dataset, basic commands to describe dataset)
```{r}
#Using the Survey dataset from MASS package.
#Description: Responses of Students at a univeristy to a number of questions. The components are Sex of the student, Writing Hand Span, Non-writing Hand Span, Writing hand of the student, Fold, Pulse Rate, Clap, Exercise, Smoke, Height of the student in cm and Age of the student.
str(df)
class(df)
typeof(df)
nrow(df)
ncol(df)
dim(df)
summary(df)
colnames(df)
head(df)
```

* * *

## Part 2: Selected Questions and Corresponding Code & Output
```{r}
#1. Calculating the avg of all rows for Wr.Hnd Span and NW.Hnd
colMeans(df[,2:3])
```
```{r}
#2. Finding the min and max of Wr. Hnd Span
min(df[,2])
max(df[,2])
```


```{r}
#3. Finding the min and max of NW. Hnd Span
min(df[,3])
max(df[,3])
```
```{r}
#4. Finding the average pulse rate of students
colMeans(df[6])
```

```{r}
#5. Display the Student row with highest pulse rate
df[which.max(df$Pulse),]
```


```{r}
#6. Display all Student rows with pulse rate higher than the average
mean(df$Pulse) #74.02381
df[which(df$Pulse>mean(df$Pulse)),]
```
```{r}
#7. Display all student rows with height above 170cm and pulse above 70
df[which((df$Height>170) & (df$Pulse>70)),]
```
```{r}
#8. Display categories in Smoke column
unique(df$Smoke)
```
```{r}
#9. Finding the average of Wr.Hnd span and NW.Hnd span
avg=c(rowMeans(df[,2:3]))
avg
```
```{r}
#10. Adding the avg column to the dataset
cbind(df,avg)
```
```{r}
#11. Display Pulse rate and height of Students above 20 years old
df[which(df$Age>20), c(6,10,12)]
```
```{r}
#12. Display Wr.Hnd Span of Right handed Students
df[which(df$W.Hnd=="Right"), 2]
```
```{r}
#13. Display the average of Wr.Hnd Span of all Left handed Students
mean(df[which(df$W.Hnd=="Left"), 2])
```


* * *





