---
title: "Excersise- 6A"


output: html_document
---
### Reg. No: 18BCE1010

### Name:R. Harini


## Setup


### Load packages if any using library(packagename)

```{r}
#1.
library(MASS)
library(dplyr)
rm(list=ls())
```

### Questions

```{r}
#2
sum(is.na(survey))
```


```{r}
#3
newsurvey=na.omit(survey)
```

```{r}
#4
table(newsurvey$Sex)
```


```{r}
#5
table(newsurvey$W.Hnd)

```

```{r}
#6
freq=table(newsurvey$W.Hnd)
rel=freq/nrow(newsurvey)
round(rel,2)
```

```{r}
#7
c=newsurvey[which(newsurvey$W.Hnd=='Left'),]
cbind(table(c$Sex))
```

```{r}
#8
c=newsurvey[which(newsurvey$Sex=='Male'& newsurvey$W.Hnd=='Left'),]
d=c[which(c$Smoke=='Never'),]
perc=nrow(d)/nrow(c)*100
perc

```


```{r}
#9
range(newsurvey$Age)
```

```{r}
#10
round(range(newsurvey$Age))
breaks<-round(seq(17,70,by=10))
Age_split<-cut(newsurvey$Age,breaks,right=F)
Age_split_freq<-table(Age_split)
Age_split_freq
```

```{r}
#11
df<-cbind(Age_split_freq)
df

```

```{r}
#12
which.max(Age_split_freq)
```

```{r}
#13
range(newsurvey$Wr.Hnd)
breaks<-round(seq(13.0,23.2,by=1.0))
Wr.Hnd_split<-cut(newsurvey$Wr.Hnd,breaks,right=F)
Wr.Hnd_split_freq<-table(Wr.Hnd_split)
df<-cbind(Wr.Hnd_split_freq)
df
```


```{r}
#14
rel=Wr.Hnd_split_freq/nrow(newsurvey)
cbind(round(rel,3))
```

```{r}
#15
mean(newsurvey$Age)
```

```{r}
#16
sd(newsurvey$Height)
var(newsurvey$Height)
```

```{r}
#17
quantile(newsurvey$Wr.Hnd)
```

```{r}
#18
cor(newsurvey$Wr.Hnd, newsurvey$Pulse)
```

```{r}
#19
tapply(newsurvey$Age, newsurvey$Exer, mean)
```

```{r}
#20
options(digits=2)
tapply(newsurvey$Height,newsurvey$NW.Hnd, sd)
```

```{r}
#21
summary(newsurvey$Pulse)
```

