---
title: "Lab5 "
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---
### Reg. No: 18BCE1010

### Name:R. Harini

## Setup


### Load packages if any using library(packagename)


### Load data
```{r}
rm(list=ls())

library(MASS)
library(dplyr)

df=na.omit(survey)

```
# 5-A


```{r}
#1
c=df%>%
  group_by(Sex)%>%
  tally()
c=pull(c,n)
barplot(c, main="Male and Female participants", ylab = "frequency", col=c("blue", "red"), names.arg = levels(df$Sex))

```


```{r}
#2
c=df%>%
  group_by(W.Hnd)%>%
  tally()
c=pull(c)
barplot(c, main="Left Handers and Right Handers", ylab="count", col=c("yellow", "green"), names.arg=levels(df$W.Hnd))

```


```{r}
#3
c=df%>%
  filter(W.Hnd=="Left")%>%
  group_by(Sex)%>%
  tally()
c=pull(c)
barplot(c,main="Female left handers and Male Left Handers", ylab="count", col=c("blue", "yellow"), names.arg=levels(df$Sex))

```


```{r}
#4
c=df%>%
  filter(Sex=="Male" & W.Hnd=="Left")%>%
  group_by(Smoke)%>%
  tally()
c=pull(c,n)
pie(c, levels(df$Smoke), main="Smoking Habits of Male Left Handers")

```

```{r}
#5.
hist(df$Age, main="Age Distribution", xlab="Age range", ylab="Frequency", col="light blue")

```

```{r}
#6
plot(df$Age, df$Wr.Hnd)
```


```{r}
#7
boxplot(df$Pulse, main="Pulse Rate", ylab="Pulse values", xlab="Pulse")
summary(df$Pulse)

```


# 5-B

```{r}
#1
#install.packages("ggplot2")
library(ggplot2)
```

```{r}
#2
ggplot(df, aes(x=Sex))+geom_bar(fill=c("red", "blue"))+ggtitle("Male and Female Participants")
```


```{r}
#3
ggplot(df, aes(x=W.Hnd))+geom_bar(fill=c("yellow", "green"))+ggtitle("Left and Right Handers")
```

```{r}
#4
c=df%>%
  filter(W.Hnd=="Left")
ggplot(c, aes(x=Sex))+geom_bar(fill=c("blue", "yellow"))+ggtitle("Female and Male Left Handers")

```

```{r}
#5
c=df%>%
  filter(Sex=="Male" & W.Hnd=="Left")
ggplot(c, aes(x=Age,y=Smoke, fill=Smoke))+geom_bar(stat="identity", width=1)+coord_polar("y", start=0)


```


```{r}
#6
ggplot(df, aes(x=Age))+geom_histogram(fill="light blue")+ggtitle("Age Distribution")+ylab("Frequency")+xlab("Age Range")

```

```{r}
#7
ggplot(df, aes(x=Age, y=Wr.Hnd))+geom_point()
```

```{r}

#8
c=df%>%
  filter(W.Hnd=="Left")
ggplot(c, aes(x=Wr.Hnd, y=Pulse,color=Sex, size=Height))+geom_point()

```

```{r}
#9
ggplot(df , aes(x=Sex, y= Height,color=Sex)) +geom_point()+facet_wrap(~W.Hnd)

```

```{r}
#10
ggplot(df,aes(x=Wr.Hnd,y=NW.Hnd,color=W.Hnd))+geom_point()+facet_wrap(~Clap)+labs(title = "claps")

```

```{r}
#11
ggplot(df,aes(x=Exer,y=Age))+geom_point()+facet_wrap(~Sex)

```

```{r}
#12
ggplot(df,aes(x=Smoke,y=Wr.Hnd))+geom_boxplot()

```


* * *




